{{- if not .Values.auth.existingSecret }}
{{- $secretName := include "polardb-for-postgresql.secretName" . }}
{{- $password := .Values.auth.password }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName }}
{{- if and (not $password) $existingSecret (hasKey $existingSecret.data .Values.auth.passwordKey) }}
{{- $password = index $existingSecret.data .Values.auth.passwordKey | b64dec }}
{{- end }}
{{- if not $password }}
{{- $password = randAlphaNum 32 }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "polardb-for-postgresql.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.auth.passwordKey }}: {{ $password | b64enc | quote }}
  {{- if .Values.ferretdb.enabled }}
  {{- $user := urlquery .Values.auth.user }}
  {{- $passwordForUrl := urlquery $password }}
  {{- $database := urlquery .Values.auth.database }}
  {{- $host := include "polardb-for-postgresql.polardbServiceName" . }}
  {{- $ferretdbPostgresqlUrl := printf "postgres://%s:%s@%s:%v/%s?sslmode=disable" $user $passwordForUrl $host (.Values.polardb.port | int) $database }}
  {{ .Values.auth.ferretdbPostgresqlUrlKey }}: {{ $ferretdbPostgresqlUrl | b64enc | quote }}
  {{- end }}
{{- end }}
