apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "polardb-postgresql.scriptsTplName" . }}
  labels:
    {{- include "polardb-postgresql.labels" . | nindent 4 }}
  annotations:
    {{- include "polardb-postgresql.annotations" . | nindent 4 }}
data:
{{- range $path, $_ := .Files.Glob "scripts/*" }}
  {{ base $path }}: |-
{{ $.Files.Get $path | indent 4 }}
{{- end }}
